#!/usr/bin/env python3
"""
scripts/validate.py
───────────────────
OPA Policy Evaluation Glue Script

Orchestrates the full Security-as-Code validation pipeline:
  1. Accepts a Terraform plan JSON file as input
  2. Invokes the OPA CLI against all policies in the policies/ directory
  3. Collects all denial messages produced by the deny rules
  4. Renders a formatted compliance report to stdout and to a file
  5. Exits with code 0 (all policies passed) or 1 (violations found)

Usage:
    python scripts/validate.py --plan <path_to_plan.json>
    python scripts/validate.py --plan <path> --policies <dir> --output <file>

Exit codes:
    0  All policies passed — infrastructure is compliant
    1  One or more policy violations found — deployment should be blocked
    2  Script error (bad arguments, OPA not found, parse failure)
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone

# ──────────────────────────────────────────────────────────────────────────────
# Constants
# ──────────────────────────────────────────────────────────────────────────────

OPA_QUERY    = "data.terraform.security.deny"
DEFAULT_POLICIES_DIR = "policies"
DEFAULT_REPORT_DIR   = "reports"
DEFAULT_REPORT_FILE  = os.path.join(DEFAULT_REPORT_DIR, "compliance_report.txt")

LINE_WIDE  = "=" * 62
LINE_THIN  = "-" * 62

# ──────────────────────────────────────────────────────────────────────────────
# Argument Parsing
# ──────────────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Evaluate a Terraform plan JSON against OPA security policies "
            "and produce a pass/fail compliance report."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python scripts/validate.py --plan tests/plan_non_compliant.json\n"
            "  python scripts/validate.py --plan plan.json --policies policies/ --output reports/out.txt"
        ),
    )
    parser.add_argument(
        "--plan",
        required=True,
        metavar="PATH",
        help="Path to the Terraform plan JSON file (generated by `terraform show -json`).",
    )
    parser.add_argument(
        "--policies",
        default=DEFAULT_POLICIES_DIR,
        metavar="DIR",
        help=f"Directory containing .rego policy files. Default: {DEFAULT_POLICIES_DIR}/",
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_REPORT_FILE,
        metavar="FILE",
        help=f"File path to write the compliance report. Default: {DEFAULT_REPORT_FILE}",
    )
    return parser.parse_args()

# ──────────────────────────────────────────────────────────────────────────────
# Input Validation
# ──────────────────────────────────────────────────────────────────────────────

def validate_inputs(plan_path: str, policies_dir: str) -> None:
    """Raise RuntimeError with a clear message if inputs are invalid."""
    if not os.path.isfile(plan_path):
        raise RuntimeError(
            f"Plan file not found: {plan_path}\n"
            "        Generate it with: terraform plan -out=tfplan && terraform show -json tfplan > plan.json"
        )

    if not os.path.isdir(policies_dir):
        raise RuntimeError(f"Policies directory not found: {policies_dir}")

    rego_files = [f for f in os.listdir(policies_dir) if f.endswith(".rego")]
    if not rego_files:
        raise RuntimeError(f"No .rego files found in: {policies_dir}")

    print(f"  Plan file    : {plan_path}")
    print(f"  Policies dir : {policies_dir}  ({len(rego_files)} policy file(s): {', '.join(rego_files)})")
    print(f"  OPA query    : {OPA_QUERY}")

# ──────────────────────────────────────────────────────────────────────────────
# OPA Evaluation
# ──────────────────────────────────────────────────────────────────────────────

def run_opa_eval(plan_path: str, policies_dir: str) -> list:
    """
    Invoke the OPA CLI and return a sorted list of denial message strings.

    OPA exits with code 0 when the query succeeds (even if the result is empty).
    It exits with a non-zero code for usage errors. We treat anything other than
    0 as an unexpected failure.
    """
    cmd = [
        "opa", "eval",
        "--format", "json",
        "--input",  plan_path,
        "--data",   policies_dir,
        OPA_QUERY,
    ]

    print(f"\n  Running: {' '.join(cmd)}\n")

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=False,
        )
    except FileNotFoundError:
        raise RuntimeError(
            "OPA CLI not found on PATH.\n"
            "        Install from: https://www.openpolicyagent.org/docs/latest/#running-opa"
        )

    if result.returncode != 0:
        parts = [f"OPA exited with non-zero code: {result.returncode}"]
        if result.stdout.strip():
            parts.append(f"OPA stdout:\n{result.stdout.strip()}")
        if result.stderr.strip():
            parts.append(f"OPA stderr:\n{result.stderr.strip()}")
        if len(parts) == 1:
            parts.append("(no output captured — check that the plan file and policy paths are correct)")
        raise RuntimeError("\n\n".join(parts))

    # Parse OPA's JSON output
    try:
        opa_output = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError(
            f"Could not parse OPA output as JSON: {exc}\n\n"
            f"Raw OPA stdout:\n{result.stdout}"
        )

    # Navigate the OPA result structure to extract the deny set
    # Structure: { "result": [ { "expressions": [ { "value": [...] } ] } ] }
    try:
        denials = opa_output["result"][0]["expressions"][0]["value"]
    except (KeyError, IndexError):
        # An empty result means no violations — treat as empty list
        denials = []

    # Return sorted for deterministic, diff-friendly output
    return sorted(denials)

# ──────────────────────────────────────────────────────────────────────────────
# Report Generation
# ──────────────────────────────────────────────────────────────────────────────

def build_report(plan_path: str, denials: list) -> str:
    """Build and return a formatted compliance report as a string."""
    now        = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    violation_count = len(denials)
    status     = "NON-COMPLIANT  ❌" if denials else "COMPLIANT      ✅"

    lines = [
        "",
        LINE_WIDE,
        "  SECURITY-AS-CODE — COMPLIANCE REPORT",
        LINE_WIDE,
        f"  Timestamp   : {now}",
        f"  Plan File   : {os.path.abspath(plan_path)}",
        f"  Policies    : {OPA_QUERY}",
        f"  Status      : {status}",
        f"  Violations  : {violation_count}",
        LINE_WIDE,
    ]

    if denials:
        lines.append("")
        lines.append("  POLICY VIOLATIONS FOUND")
        lines.append("  " + LINE_THIN)
        for idx, msg in enumerate(denials, start=1):
            lines.append(f"  [{idx:02d}] {msg}")
        lines.append("")
        lines.append("  " + LINE_THIN)
        lines.append("  ⛔  ACTION REQUIRED: Resolve all violations before deployment.")
        lines.append("      Fix the Terraform configuration and re-run the pipeline.")
    else:
        lines.append("")
        lines.append("  ✅  All security policies passed.")
        lines.append("      Infrastructure configuration is compliant.")
        lines.append("      Safe to proceed with deployment.")

    lines.append("")
    lines.append(LINE_WIDE)
    lines.append("")

    return "\n".join(lines)


def build_error_report(error_msg: str) -> str:
    """Build a formatted report for pipeline errors (OPA not found, bad plan, etc.)."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        "",
        LINE_WIDE,
        "  SECURITY-AS-CODE — COMPLIANCE REPORT",
        LINE_WIDE,
        f"  Timestamp   : {now}",
        f"  Status      : PIPELINE ERROR  ⚠️",
        LINE_WIDE,
        "",
        "  PIPELINE ERROR — OPA EVALUATION DID NOT COMPLETE",
        "  " + LINE_THIN,
    ]
    for line in error_msg.splitlines():
        lines.append(f"  {line}")
    lines += [
        "",
        "  " + LINE_THIN,
        "  ⚠️  Check the workflow logs for the failed step above.",
        "",
        LINE_WIDE,
        "",
    ]

    return "\n".join(lines)

# ──────────────────────────────────────────────────────────────────────────────
# Report Writer
# ──────────────────────────────────────────────────────────────────────────────

def write_report(report: str, output_path: str) -> None:
    """Write the compliance report to a file, creating parent dirs if needed."""
    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(report)

    print(f"  Report saved : {os.path.abspath(output_path)}")

# ──────────────────────────────────────────────────────────────────────────────
# Entry Point
# ──────────────────────────────────────────────────────────────────────────────

def main() -> None:
    args = parse_args()

    print("\n" + LINE_WIDE)
    print("  Security-as-Code — OPA Policy Evaluator")
    print(LINE_WIDE)

    exit_code = 2
    try:
        # Step 1: Validate inputs
        validate_inputs(args.plan, args.policies)

        # Step 2: Run OPA CLI
        denials = run_opa_eval(args.plan, args.policies)

        # Step 3: Build report
        report = build_report(args.plan, denials)

        # Step 4: Print to stdout
        print(report)

        # Step 5: Save to file
        write_report(report, args.output)

        # Step 6: Set exit code
        #   0 → compliant (CI pipeline continues)
        #   1 → violations found (CI pipeline fails and blocks merge)
        exit_code = 1 if denials else 0

    except RuntimeError as exc:
        print(f"\n[ERROR] {exc}", file=sys.stderr)
        error_report = build_error_report(str(exc))
        print(error_report)
        write_report(error_report, args.output)
        exit_code = 2

    sys.exit(exit_code)


if __name__ == "__main__":
    main()
